name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 4 * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_HUB_DEPLOY_KEY }}
    - name: Build the Docker image
      run: |
        docker build . --tag mietzen/synology-collabora:$(date -I)
        docker tag mietzen/synology-collabora:$(date -I) mietzen/synology-collabora:latest
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u mietzen --password-stdin
        docker push -a mietzen/synology-collabora
        docker logout
