name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_DEPLOY_KEY }}
  
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      run: |
        docker build . --tag "${DOCKER_USER}/synology-collabora:$(date -I)"
        docker tag "${DOCKER_USER}/synology-collabora:$(date -I)" "${DOCKER_USER}/synology-collabora:latest"
        docker push -a "${DOCKER_USER}/synology-collabora"
